package br.com.fiap.s3a.domain.enums;

public enum TipoAlerta {
    CAVIDADE_DETECTADA, AQUIFERO_PROVAVEL, TUBO_LAVA_DETECTADO,
    FALHA_ENERGETICA, FALHA_COMUNICACAO, FALHA_SENSOR,
    MARSQUAKE_DETECTADO, BATERIA_CRITICA
}